version: "3"
services:

  front:
    container_name: front
    image: nazhu21/quotes-front:v1
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    container_name: api
    image: nazhu21/quotes-back:v1
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    container_name: db
    image: nazhu21/quotes-data:v2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    container_name: data-script
    image: nazhu21/quotes-script:v1
    networks:
      - myapp

networks:
  myapp:
